// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0opiGkXXL4SDkOmiubngLYSg0Lr9woig',
    appId: '1:71972361225:web:3467d1851f311a556454d8',
    messagingSenderId: '71972361225',
    projectId: 'share-costs-app-data',
    authDomain: 'share-costs-app-data.firebaseapp.com',
    storageBucket: 'share-costs-app-data.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSZiCEq-ix0-BdqKhqfBe0tHh2qmbU1iA',
    appId: '1:71972361225:android:0d220ded89ff194e6454d8',
    messagingSenderId: '71972361225',
    projectId: 'share-costs-app-data',
    storageBucket: 'share-costs-app-data.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC54X24-MtNW6sElOhPQOxorq46A7GZww',
    appId: '1:71972361225:ios:881243bb430cf68c6454d8',
    messagingSenderId: '71972361225',
    projectId: 'share-costs-app-data',
    storageBucket: 'share-costs-app-data.appspot.com',
    iosClientId: '71972361225-gtc4af6j16v2lsrbe60k4u86kcgdeopt.apps.googleusercontent.com',
    iosBundleId: 'com.example.shareCostApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC54X24-MtNW6sElOhPQOxorq46A7GZww',
    appId: '1:71972361225:ios:881243bb430cf68c6454d8',
    messagingSenderId: '71972361225',
    projectId: 'share-costs-app-data',
    storageBucket: 'share-costs-app-data.appspot.com',
    iosClientId: '71972361225-gtc4af6j16v2lsrbe60k4u86kcgdeopt.apps.googleusercontent.com',
    iosBundleId: 'com.example.shareCostApp',
  );
}
